### PR TITLE
Add new Game of thrones animation

### PR DESCRIPTION
**Pull request by jbampton**

### CODE REVIEW

**Comment by jbampton** [comment]
Hey @prestonhunter can you look and approve the Percy shots ?

**Comment by prestonhunter** [comment]
re: "Hey @prestonhunter <https://github.com/prestonhunter> can you look and
approve the Percy shots"

Is that through GitHub? #84?

**Comment by jbampton** [comment]
Yes

**Comment by prestonhunter** [comment]
I'll certainly try.
Have not worked with Percy yet, but maybe this will be the time to learn
how to do so...

**Comment by jbampton** [comment]
Looks like they can all be approved since they are new snapshots at a new width

**Comment by prestonhunter** [comment]
Ah... So I don't necessarily need to use Percy in order to view and approve
these?

**Pull request merged**
